import google.generativeai as genai
import os

def load_story_template():
    """Load story template from prompt_template/template.txt"""
    template_data = {}
    template_path = "prompt_template/template.txt"
    
    try:
        with open(template_path, "r", encoding='utf-8') as file:
            content = file.read()
            for line in content.split('\n'):
                if ":" in line and line.strip():
                    key, value = line.strip().split(":", 1)
                    template_data[key.strip().lower()] = value.strip()
        print(f"Template loaded from {template_path}")
    except FileNotFoundError:
        print(f"Template file not found at {template_path}, using default template")

def create_story(user_input):
    """Generate story using Gemini AI with user input"""
    
    # Load template
    story_template = load_story_template()
    
    # Extract user inputs
    character = user_input.get("character", "Unknown character")
    setting = user_input.get("setting", "Unknown setting")
    theme = user_input.get("theme", "Adventure")
    age_group = user_input.get("age_group", "All ages")

    # Build the prompt
    story_prompt = f"""
{story_template.get('role', 'You are a creative storyteller.')}

{story_template.get('task', 'Generate an engaging story.')}

Story Requirements:
- Character: {character}
- Setting: {setting}  
- Theme: {theme}
- Target Age Group: {age_group}

Instructions: {story_template.get('instructions', 'Create a well-structured story.')}

Important: {story_template.get('negative prompt', 'Keep content appropriate for the age group.')}

Please generate a complete story that incorporates all these elements.
"""

    print("=" * 60)
    print(" PROMPT BEING SENT TO GEMINI:")
    print(story_prompt)
    print("=" * 60)

    try:
        # Use Gemini 1.5 Flash (correct model name)
        model = genai.GenerativeModel(model_name="gemini-1.5-flash")
        
        # Generate content
        response = model.generate_content(story_prompt)
        
        if response.text:
            generated_story = response.text.strip()
            print(" Story generated successfully!")
            return generated_story
        else:
            raise Exception("No story text generated by Gemini")
            
    except Exception as api_error:
        print(f" Error from Gemini API: {api_error}")
        # Re-raise with more context
        raise Exception(f"Gemini API Error: {api_error}")

def validate_story_input(input_data):
    """Validate the input data for story generation"""
    required_fields = ["character", "setting", "theme", "age_group"]
    
    if not isinstance(input_data, dict):
        return False, "Input must be a dictionary"

    return True, "Valid input"
